/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as StoryboardRouteImport } from './routes/storyboard'
import { Route as PromptRouteImport } from './routes/prompt'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImageRouteImport } from './routes/image'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVideoPromptRouteImport } from './routes/api/video-prompt'
import { Route as ApiVerifyGeminiRouteImport } from './routes/api/verify-gemini'
import { Route as ApiTransformImageRouteImport } from './routes/api/transform-image'
import { Route as ApiStoryboardSceneRouteImport } from './routes/api/storyboard-scene'
import { Route as ApiKeyframesRouteImport } from './routes/api/keyframes'
import { Route as ApiGenerateVideoRouteImport } from './routes/api/generate-video'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiExpandPromptRouteImport } from './routes/api/expand-prompt'
import { Route as ApiDirectorAiRouteImport } from './routes/api/director-ai'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryboardRoute = StoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptRoute = PromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoPromptRoute = ApiVideoPromptRouteImport.update({
  id: '/api/video-prompt',
  path: '/api/video-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyGeminiRoute = ApiVerifyGeminiRouteImport.update({
  id: '/api/verify-gemini',
  path: '/api/verify-gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransformImageRoute = ApiTransformImageRouteImport.update({
  id: '/api/transform-image',
  path: '/api/transform-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryboardSceneRoute = ApiStoryboardSceneRouteImport.update({
  id: '/api/storyboard-scene',
  path: '/api/storyboard-scene',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeyframesRoute = ApiKeyframesRouteImport.update({
  id: '/api/keyframes',
  path: '/api/keyframes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVideoRoute = ApiGenerateVideoRouteImport.update({
  id: '/api/generate-video',
  path: '/api/generate-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpandPromptRoute = ApiExpandPromptRouteImport.update({
  id: '/api/expand-prompt',
  path: '/api/expand-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectorAiRoute = ApiDirectorAiRouteImport.update({
  id: '/api/director-ai',
  path: '/api/director-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/director': typeof DirectorRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/image': typeof ImageRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/prompt': typeof PromptRoute
  '/storyboard': typeof StoryboardRoute
  '/topup': typeof TopupRoute
  '/video': typeof VideoRoute
  '/api/director-ai': typeof ApiDirectorAiRoute
  '/api/expand-prompt': typeof ApiExpandPromptRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/keyframes': typeof ApiKeyframesRoute
  '/api/storyboard-scene': typeof ApiStoryboardSceneRoute
  '/api/transform-image': typeof ApiTransformImageRoute
  '/api/verify-gemini': typeof ApiVerifyGeminiRoute
  '/api/video-prompt': typeof ApiVideoPromptRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/director': typeof DirectorRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/image': typeof ImageRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/prompt': typeof PromptRoute
  '/storyboard': typeof StoryboardRoute
  '/topup': typeof TopupRoute
  '/video': typeof VideoRoute
  '/api/director-ai': typeof ApiDirectorAiRoute
  '/api/expand-prompt': typeof ApiExpandPromptRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/keyframes': typeof ApiKeyframesRoute
  '/api/storyboard-scene': typeof ApiStoryboardSceneRoute
  '/api/transform-image': typeof ApiTransformImageRoute
  '/api/verify-gemini': typeof ApiVerifyGeminiRoute
  '/api/video-prompt': typeof ApiVideoPromptRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/director': typeof DirectorRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/image': typeof ImageRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/prompt': typeof PromptRoute
  '/storyboard': typeof StoryboardRoute
  '/topup': typeof TopupRoute
  '/video': typeof VideoRoute
  '/api/director-ai': typeof ApiDirectorAiRoute
  '/api/expand-prompt': typeof ApiExpandPromptRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/keyframes': typeof ApiKeyframesRoute
  '/api/storyboard-scene': typeof ApiStoryboardSceneRoute
  '/api/transform-image': typeof ApiTransformImageRoute
  '/api/verify-gemini': typeof ApiVerifyGeminiRoute
  '/api/video-prompt': typeof ApiVideoPromptRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/director'
    | '/history'
    | '/home'
    | '/image'
    | '/login'
    | '/profile'
    | '/prompt'
    | '/storyboard'
    | '/topup'
    | '/video'
    | '/api/director-ai'
    | '/api/expand-prompt'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/keyframes'
    | '/api/storyboard-scene'
    | '/api/transform-image'
    | '/api/verify-gemini'
    | '/api/video-prompt'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/director'
    | '/history'
    | '/home'
    | '/image'
    | '/login'
    | '/profile'
    | '/prompt'
    | '/storyboard'
    | '/topup'
    | '/video'
    | '/api/director-ai'
    | '/api/expand-prompt'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/keyframes'
    | '/api/storyboard-scene'
    | '/api/transform-image'
    | '/api/verify-gemini'
    | '/api/video-prompt'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/director'
    | '/history'
    | '/home'
    | '/image'
    | '/login'
    | '/profile'
    | '/prompt'
    | '/storyboard'
    | '/topup'
    | '/video'
    | '/api/director-ai'
    | '/api/expand-prompt'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/keyframes'
    | '/api/storyboard-scene'
    | '/api/transform-image'
    | '/api/verify-gemini'
    | '/api/video-prompt'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectorRoute: typeof DirectorRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  ImageRoute: typeof ImageRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  PromptRoute: typeof PromptRoute
  StoryboardRoute: typeof StoryboardRoute
  TopupRoute: typeof TopupRoute
  VideoRoute: typeof VideoRoute
  ApiDirectorAiRoute: typeof ApiDirectorAiRoute
  ApiExpandPromptRoute: typeof ApiExpandPromptRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGenerateVideoRoute: typeof ApiGenerateVideoRoute
  ApiKeyframesRoute: typeof ApiKeyframesRoute
  ApiStoryboardSceneRoute: typeof ApiStoryboardSceneRoute
  ApiTransformImageRoute: typeof ApiTransformImageRoute
  ApiVerifyGeminiRoute: typeof ApiVerifyGeminiRoute
  ApiVideoPromptRoute: typeof ApiVideoPromptRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyboard': {
      id: '/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof StoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt': {
      id: '/prompt'
      path: '/prompt'
      fullPath: '/prompt'
      preLoaderRoute: typeof PromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-prompt': {
      id: '/api/video-prompt'
      path: '/api/video-prompt'
      fullPath: '/api/video-prompt'
      preLoaderRoute: typeof ApiVideoPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-gemini': {
      id: '/api/verify-gemini'
      path: '/api/verify-gemini'
      fullPath: '/api/verify-gemini'
      preLoaderRoute: typeof ApiVerifyGeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transform-image': {
      id: '/api/transform-image'
      path: '/api/transform-image'
      fullPath: '/api/transform-image'
      preLoaderRoute: typeof ApiTransformImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storyboard-scene': {
      id: '/api/storyboard-scene'
      path: '/api/storyboard-scene'
      fullPath: '/api/storyboard-scene'
      preLoaderRoute: typeof ApiStoryboardSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keyframes': {
      id: '/api/keyframes'
      path: '/api/keyframes'
      fullPath: '/api/keyframes'
      preLoaderRoute: typeof ApiKeyframesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-video': {
      id: '/api/generate-video'
      path: '/api/generate-video'
      fullPath: '/api/generate-video'
      preLoaderRoute: typeof ApiGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expand-prompt': {
      id: '/api/expand-prompt'
      path: '/api/expand-prompt'
      fullPath: '/api/expand-prompt'
      preLoaderRoute: typeof ApiExpandPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/director-ai': {
      id: '/api/director-ai'
      path: '/api/director-ai'
      fullPath: '/api/director-ai'
      preLoaderRoute: typeof ApiDirectorAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectorRoute: DirectorRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  ImageRoute: ImageRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  PromptRoute: PromptRoute,
  StoryboardRoute: StoryboardRoute,
  TopupRoute: TopupRoute,
  VideoRoute: VideoRoute,
  ApiDirectorAiRoute: ApiDirectorAiRoute,
  ApiExpandPromptRoute: ApiExpandPromptRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGenerateVideoRoute: ApiGenerateVideoRoute,
  ApiKeyframesRoute: ApiKeyframesRoute,
  ApiStoryboardSceneRoute: ApiStoryboardSceneRoute,
  ApiTransformImageRoute: ApiTransformImageRoute,
  ApiVerifyGeminiRoute: ApiVerifyGeminiRoute,
  ApiVideoPromptRoute: ApiVideoPromptRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
