/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as StoryboardRouteImport } from './routes/storyboard'
import { Route as PromptRouteImport } from './routes/prompt'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImageRouteImport } from './routes/image'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVideoPromptRouteImport } from './routes/api/video-prompt'
import { Route as ApiVerifyGeminiRouteImport } from './routes/api/verify-gemini'
import { Route as ApiTransformImageRouteImport } from './routes/api/transform-image'
import { Route as ApiStoryboardSceneRouteImport } from './routes/api/storyboard-scene'
import { Route as ApiKeyframesRouteImport } from './routes/api/keyframes'
import { Route as ApiGenerateVideoRouteImport } from './routes/api/generate-video'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryboardRoute = StoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptRoute = PromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoPromptRoute = ApiVideoPromptRouteImport.update({
  id: '/api/video-prompt',
  path: '/api/video-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyGeminiRoute = ApiVerifyGeminiRouteImport.update({
  id: '/api/verify-gemini',
  path: '/api/verify-gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransformImageRoute = ApiTransformImageRouteImport.update({
  id: '/api/transform-image',
  path: '/api/transform-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryboardSceneRoute = ApiStoryboardSceneRouteImport.update({
  id: '/api/storyboard-scene',
  path: '/api/storyboard-scene',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeyframesRoute = ApiKeyframesRouteImport.update({
  id: '/api/keyframes',
  path: '/api/keyframes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVideoRoute = ApiGenerateVideoRouteImport.update({
  id: '/api/generate-video',
  path: '/api/generate-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/image': typeof ImageRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/prompt': typeof PromptRoute
  '/storyboard': typeof StoryboardRoute
  '/video': typeof VideoRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/keyframes': typeof ApiKeyframesRoute
  '/api/storyboard-scene': typeof ApiStoryboardSceneRoute
  '/api/transform-image': typeof ApiTransformImageRoute
  '/api/verify-gemini': typeof ApiVerifyGeminiRoute
  '/api/video-prompt': typeof ApiVideoPromptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/image': typeof ImageRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/prompt': typeof PromptRoute
  '/storyboard': typeof StoryboardRoute
  '/video': typeof VideoRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/keyframes': typeof ApiKeyframesRoute
  '/api/storyboard-scene': typeof ApiStoryboardSceneRoute
  '/api/transform-image': typeof ApiTransformImageRoute
  '/api/verify-gemini': typeof ApiVerifyGeminiRoute
  '/api/video-prompt': typeof ApiVideoPromptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/image': typeof ImageRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/prompt': typeof PromptRoute
  '/storyboard': typeof StoryboardRoute
  '/video': typeof VideoRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/keyframes': typeof ApiKeyframesRoute
  '/api/storyboard-scene': typeof ApiStoryboardSceneRoute
  '/api/transform-image': typeof ApiTransformImageRoute
  '/api/verify-gemini': typeof ApiVerifyGeminiRoute
  '/api/video-prompt': typeof ApiVideoPromptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/home'
    | '/image'
    | '/login'
    | '/profile'
    | '/prompt'
    | '/storyboard'
    | '/video'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/keyframes'
    | '/api/storyboard-scene'
    | '/api/transform-image'
    | '/api/verify-gemini'
    | '/api/video-prompt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/home'
    | '/image'
    | '/login'
    | '/profile'
    | '/prompt'
    | '/storyboard'
    | '/video'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/keyframes'
    | '/api/storyboard-scene'
    | '/api/transform-image'
    | '/api/verify-gemini'
    | '/api/video-prompt'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/home'
    | '/image'
    | '/login'
    | '/profile'
    | '/prompt'
    | '/storyboard'
    | '/video'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/keyframes'
    | '/api/storyboard-scene'
    | '/api/transform-image'
    | '/api/verify-gemini'
    | '/api/video-prompt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  ImageRoute: typeof ImageRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  PromptRoute: typeof PromptRoute
  StoryboardRoute: typeof StoryboardRoute
  VideoRoute: typeof VideoRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGenerateVideoRoute: typeof ApiGenerateVideoRoute
  ApiKeyframesRoute: typeof ApiKeyframesRoute
  ApiStoryboardSceneRoute: typeof ApiStoryboardSceneRoute
  ApiTransformImageRoute: typeof ApiTransformImageRoute
  ApiVerifyGeminiRoute: typeof ApiVerifyGeminiRoute
  ApiVideoPromptRoute: typeof ApiVideoPromptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyboard': {
      id: '/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof StoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt': {
      id: '/prompt'
      path: '/prompt'
      fullPath: '/prompt'
      preLoaderRoute: typeof PromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-prompt': {
      id: '/api/video-prompt'
      path: '/api/video-prompt'
      fullPath: '/api/video-prompt'
      preLoaderRoute: typeof ApiVideoPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-gemini': {
      id: '/api/verify-gemini'
      path: '/api/verify-gemini'
      fullPath: '/api/verify-gemini'
      preLoaderRoute: typeof ApiVerifyGeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transform-image': {
      id: '/api/transform-image'
      path: '/api/transform-image'
      fullPath: '/api/transform-image'
      preLoaderRoute: typeof ApiTransformImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storyboard-scene': {
      id: '/api/storyboard-scene'
      path: '/api/storyboard-scene'
      fullPath: '/api/storyboard-scene'
      preLoaderRoute: typeof ApiStoryboardSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keyframes': {
      id: '/api/keyframes'
      path: '/api/keyframes'
      fullPath: '/api/keyframes'
      preLoaderRoute: typeof ApiKeyframesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-video': {
      id: '/api/generate-video'
      path: '/api/generate-video'
      fullPath: '/api/generate-video'
      preLoaderRoute: typeof ApiGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  ImageRoute: ImageRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  PromptRoute: PromptRoute,
  StoryboardRoute: StoryboardRoute,
  VideoRoute: VideoRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGenerateVideoRoute: ApiGenerateVideoRoute,
  ApiKeyframesRoute: ApiKeyframesRoute,
  ApiStoryboardSceneRoute: ApiStoryboardSceneRoute,
  ApiTransformImageRoute: ApiTransformImageRoute,
  ApiVerifyGeminiRoute: ApiVerifyGeminiRoute,
  ApiVideoPromptRoute: ApiVideoPromptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
